# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Header
language: r
sudo: false
cache: packages

addons:
  apt:
    update: true
    packages:
      - libudunits2-dev # for udunits2
      - libgeos-dev # for sf
      - libproj-dev # for sf
      - libgdal-dev # for sf

before_script:
  - Rscript -e 'remotes::install_cran(c("devtools", "covr", "pkgdown", "spelling"))'
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install framed titling cancel; fi

r:
  - oldrel
  - devel

matrix:
  include:
    - r: release
      os: osx
    - r: release
      os: linux
      env: DEPLOY=true

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'spelling::spell_check_package(vignettes = TRUE)'

deploy:
  - provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
    on:
      branch: master
      condition: "$DEPLOY = true"
