---
title: "Citing articles"
author: "Maxime Lenormand, Boris Leroy and Pierre Denelle"
date: "`r Sys.Date()`"
output: 
  html_vignette:
    number_sections: false
  html_document:
    toc: true
    toc_float:
    collapsed: false
    smooth_scroll: false
    toc_depth: 2
bibliography: '`r system.file("REFERENCES.bib", package="bioregion")`' 
csl: journal-of-biogeography.csl
vignette: >
  %\VignetteIndexEntry{Citing articles}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# 2025

* Albouy C, Fopp F, Brun P, Descombes P, Altermatt F, Pellissier L & Csilléry K (2025) 
[gbif.range: An R package to generate ecologically-informed species range maps from occurrence data with seamless GBIF integration.](https://www.authorea.com/doi/full/10.22541/au.175130858.83083354) 
*Authorea* (under review).

* Zhang B, Zhou M, Xie Z, Zhang L, Duan H, Yu J & He J (2025)
[Updated Chorotypes of Terrestrial Vertebrates Shed New Light on Zoogeographical Regions in China](https://onlinelibrary.wiley.com/doi/full/10.1111/1749-4877.70025)
*Integrative Zoology* (early view). 

* Renan M, Roll U, Grabovsky VI, Shenbrot GI & Krasnov BR (2025)
[Phylogenetic Regionalization of Ectoparasites and Their Hosts Using 2 Approaches: A Case Study with Fleas and Their Rodent Hosts from Mongolia.](https://www.cambridge.org/core/journals/parasitology/article/phylogenetic-regionalization-of-ectoparasites-and-their-hosts-using-2-approaches-a-case-study-with-fleas-and-their-rodent-hosts-from-mongolia/4651F529F56A669986F9CA4F1FF23E66)
*Parasitology* (early view).

* Lampou A, Skoulikidis N & Bonada N (2025)
[Biogeographical Regions in the Aegean Archipelago: An Assessment for Freshwater Macroinvertebrates](https://onlinelibrary.wiley.com/doi/full/10.1111/jbi.70117)
*Journal of Biogeography* 53, e70117.

* Lenormand M, F&#233;ret JB, Papuga G, Alleaume S & Luque S (2025) 
[Coupling in situ and remote sensing data to assess &#945;- and &#946;-diversity over biogeographic gradients.](https://nsojournals.onlinelibrary.wiley.com/doi/full/10.1111/ecog.07479)
*Ecography* 2025, e07479.  

* Cheng Z & Ma KY (2025) [Historical Biogeography of Penaeus Prawns (Crustacea: Decapoda: Penaeidae).](https://onlinelibrary.wiley.com/doi/10.1111/jbi.70056) 
*Journal of Biogeography* 52, e70056.

* Souza Oliveira M, Lenormand M, Luque S, Zamora NA, Alleaume S, Aguilar Porras AC, 
Castillo MU, Chac&#243;n-Madrigal E, Delgado D, Hern&#225;ndez S&#225;nchez LG, Ngo Bieng M-A, 
Quesada RM, Solano GS & Z&#250;&#241;iga PM (2025) 
[Unlocking tropical forest complexity: How tree assemblages in
secondary forests boost biodiversity conservation.](https://onlinelibrary.wiley.com/doi/10.1002/ece3.72428)
*Ecology & Evolution* 15, e72428.

* Noori S, Rödder D, Yusefi GH, Hawlitschek O, Wanke D, Husemann M & Rajaei H (2025) 
[Biogeographic Patterns of Iranian Lepidoptera: A Framework for Conservation.](https://onlinelibrary.wiley.com/doi/full/10.1111/ddi.70010) 
*Diversity and Distributions* 31, e70010.

