# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

abc <- function(comat) {
    .Call(`_bioregion_abc`, comat)
}

ihct_node_sizes <- function(merge) {
    .Call(`_bioregion_ihct_node_sizes`, merge)
}

ihct_cophenetic_correlation <- function(merge, height, d) {
    .Call(`_bioregion_ihct_cophenetic_correlation`, merge, height, d)
}

