# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

abc <- function(comat) {
    .Call(`_bioregion_abc`, comat)
}

ihct_node_sizes <- function(merge) {
    .Call(`_bioregion_ihct_node_sizes`, merge)
}

ihct_shuffled_dist <- function(dist_mat, sites) {
    .Call(`_bioregion_ihct_shuffled_dist`, dist_mat, sites)
}

ihct_cophenetic_correlation <- function(merge, height, d, leaf_site = NULL) {
    .Call(`_bioregion_ihct_cophenetic_correlation`, merge, height, d, leaf_site)
}

ihct_prune_tree <- function(merge, height, pairs, leaf_site, keep, d) {
    .Call(`_bioregion_ihct_prune_tree`, merge, height, pairs, leaf_site, keep, d)
}

ihct_top_division <- function(merge, leaf_site) {
    .Call(`_bioregion_ihct_top_division`, merge, leaf_site)
}

