# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

abc <- function(comat) {
    .Call(`_bioRgeo_abc`, comat)
}

prodmat <- function(A, B) {
    .Call(`_bioRgeo_prodmat`, A, B)
}

