#' Convert similarity indices to distance indices
#'
#' This function converts a data.frame of similarity indices between sites to
#'  distance indices (= beta diversity).
#'
#' @param similaritydata the output object from \code{\link{spproject}} or a
#' \code{data.frame} with the first columns called "Site1" and "Site2", and the
#' other columns being the similarity metrics.
#' @export
#' @note
#' The behaviour of this function changes depending on column names. Columns
#' "Site1" and "Site2" are copied identically. If there are columns called
#' "a", "b", "c", "A", "B", "C", they will also be copied identically.
#'
#' If a column is called "Euclidean", its distance will be calculated based
#' on the following formula:
#'
#' \eqn{Euclidean distance = (1 - Euclidean similarity) / Euclidean similarity}
#'
#' Otherwise, all other columns will be transformed into distances with the
#' following formula:
#'
#' \eqn{distance = 1 - similarity}
#'
#'
#' @return A \code{data.frame} with additional class \code{bioRgeo.distance}
#'
#' @author
#' Pierre Denelle (\email{pierre.denelle@gmail.com}),
#' Maxime Lenormand (\email{maxime.lenormand@inrae.fr}) and
#' Boris Leroy (\email{leroy.boris@gmail.com})
#' @seealso \link{distanceToSimilarity}
#' @examples
#' comat <- matrix(sample(0:1000, size = 50, replace = TRUE, prob = 1/1:1001), 5, 10)
#' rownames(comat) <- paste0("Site",1:5)
#' colnames(comat) <- paste0("Species",1:10)
#'
#' simil <- spproject(comat, metric = "all")
#' simil
#'
#' distances <- similarityToDistance(simil)
#' distances
similarityToDistance <- function(similaritydata)
{
  if(inherits(similaritydata, "bioRgeo.distance"))
  {
    stop("similaritydata is already composed of similarity indices. If you want to convert it to similarity, use distanceToSimilarity()")
  }

  distancedata <- similaritydata

  if(inherits(similaritydata, "bioRgeo.similarity"))
  {
    # Overwrite class
    class(distancedata)[class(distancedata) == "bioRgeo.similarity"] <- "bioRgeo.distance"
  } else
  {
    warning("similaritydata was not generated by bioRgeo. Wrong behaviour may happen.\n")
    # Create output class
    class(distancedata) <- append("bioRgeo.distance", class(distancedata))
  }

  metrics <- colnames(similaritydata)[-which(colnames(similaritydata) %in% c("Site1", "Site2", "a", "b", "c", "A", "B", "C"))]

  # Special case for Euclidean distances
  if("Euclidean" %in% metrics)
  {
    distancedata[, "Euclidean"] <- (1 - similaritydata[, "Euclidean"]) / similaritydata[, "Euclidean"]
    metrics <- metrics[-which(metrics == "Euclidean")]
  }
  # If there are other metrics than Euclidean, we use the same formula for all fo them
  if(length(metrics))
  {
    distancedata[, metrics] <- 1 - similaritydata[, metrics]
  }

  return(distancedata)
}

#' Convert distance indices to similarity indices
#'
#' This function converts a data.frame of distance indices (beta diversity)
#' between sites to similarity indices.
#'
#' @param distancedata the output object from \code{\link{similarityToDistance}} or a
#' \code{data.frame} with the first columns called "Site1" and "Site2", and the
#' other columns being the similarity metrics.
#' @export
#' @note
#' The behaviour of this function changes depending on column names. Columns
#' "Site1" and "Site2" are copied identically. If there are columns called
#' "a", "b", "c", "A", "B", "C", they will also be copied identically.
#'
#' If a column is called "Euclidean", its similarity will be calculated based
#' on the following formula:
#'
#' \eqn{Euclidean similarity = (1 - Euclidean distance) / Euclidean distance}
#'
#' Otherwise, all other columns will be transformed into similarity with the
#' following formula:
#'
#' \eqn{similarity = 1 - distance}
#'
#'
#' @return A \code{data.frame} with additional class \code{bioRgeo.similarity}
#'
#' @author
#' Pierre Denelle (\email{pierre.denelle@gmail.com}),
#' Maxime Lenormand (\email{maxime.lenormand@inrae.fr}) and
#' Boris Leroy (\email{leroy.boris@gmail.com})
#' @seealso \link{distanceToSimilarity}
#' @examples
#' comat <- matrix(sample(0:1000, size = 50, replace = TRUE, prob = 1/1:1001), 5, 10)
#' rownames(comat) <- paste0("Site",1:5)
#' colnames(comat) <- paste0("Species",1:10)
#'
#' simil <- spproject(comat, metric = "all")
#' simil
#'
#' distances <- similarityToDistance(simil)
#' distances
#'
#' simil <- distanceToSimilarity(distances)
#' simil
distanceToSimilarity <- function(distancedata)
{
  if(inherits(distancedata, "bioRgeo.similarity"))
  {
    stop("distancedata is already composed of distance indices. If you want to convert it to similarity, use similarityToDistance()")
  }

  similaritydata <- distancedata

  if(inherits(distancedata, "bioRgeo.distance"))
  {
    # Overwrite class
    class(similaritydata)[class(similaritydata) == "bioRgeo.distance"] <- "bioRgeo.similarity"
  } else
  {
    warning("similaritydata was not generated by bioRgeo. Wrong behaviour may happen.\n")
    # Create output class
    class(similaritydata) <- append("bioRgeo.similarity", class(similaritydata))
  }

  metrics <- colnames(distancedata)[-which(colnames(distancedata) %in% c("Site1", "Site2", "a", "b", "c", "A", "B", "C"))]
  # Special case for Euclidean distances
  if("Euclidean" %in% metrics)
  {
    similaritydata[, "Euclidean"] <- 1 / (1 + distancedata[, "Euclidean"])
    metrics <- metrics[-which(metrics == "Euclidean")]
  }
  # If there are other metrics than Euclidean, we use the same formula for all fo them
  if(length(metrics))
  {
    similaritydata[, metrics] <- 1 - similaritydata[, metrics]
  }

  # Create output class
  return(similaritydata)
}
